import Head from 'next/head'
import PetDetail from '@/components/pets/PetDetail'

export default function PetDetailPage() {
    return (
        <>
            <Head>
                <title>Detalle de mascota</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <PetDetail />
            </main>
        </>
    )
}
