import Head from 'next/head'
import Pets from '@/components/pets/Pets'

export default function PetsPage() {
    return (
        <>
            <Head>
                <title>Mascotas</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Pets />
            </main>
        </>
    )
}
