import Head from 'next/head'
import AddPetSuccess from '@/components/add-pet/AddPetSuccess'

export default function AddPetPage() {
    return (
        <>
            <Head>
                <title>Mascota agregada</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <AddPetSuccess />
            </main>
        </>
    )
}
